#!/usr/bin/env bash
# Generates docs/ROUTES.md — a sorted inventory of page routes derived from
# the src/app/ App Router directory structure. Deterministic: two runs on the
# same tree are byte-identical apart from the generation date.
#
# Usage: scripts/gen-docs.sh [output-file]   (default: docs/ROUTES.md)
# Freshness is gated by scripts/check-freshness.sh (CI: freshness.yml).
set -euo pipefail

root=$(cd "$(dirname "$0")/.." && pwd)
out="${1:-$root/docs/ROUTES.md}"

# One row per page file: "| `<route>` | `<source>` |", sorted by route path.
# Route-group segments like (cm) are stripped — they do not appear in the URL.
rows=$(
  cd "$root"
  find src/app -type f \( -name 'page.tsx' -o -name 'page.ts' -o -name 'page.jsx' -o -name 'page.js' \) \
    | while IFS= read -r f; do
        rel="${f#src/app}"                       # /(cm)/about/page.tsx
        route=$(dirname "$rel")                  # /(cm)/about
        route=$(printf '%s' "$route" | sed -E 's#/\([^/)]+\)##g')
        [ -z "$route" ] || [ "$route" = "/" ] && route="/"
        printf '| `%s` | `%s` |\n' "$route" "$f"
      done \
    | LC_ALL=C sort
)

count=$(printf '%s\n' "$rows" | grep -c '^|')

{
  echo "# Website Routes — GENERATED"
  echo ""
  echo "> Generated by \`scripts/gen-docs.sh\` from \`src/app/**/page.tsx\` on $(date +%Y-%m-%d)."
  echo "> Do not hand-edit — \`scripts/check-freshness.sh\` fails on drift."
  echo ""
  echo "| Route | Source |"
  echo "| --- | --- |"
  printf '%s\n' "$rows"
  echo ""
  echo "${count} page routes."
} > "$out"
